export const jobSkills = [
  "communication",
  "teamwork",
  "problem solving",
  "time management",
  "adaptability",
  "critical thinking",
  "leadership",
  "attention to detail",
  "project management",
  "interpersonal skills",
  "organizational skills",
  "creativity",
  "emotional intelligence",
  "collaboration",
  "decision making",
  "conflict resolution",
  "multitasking",
  "negotiation",
  "analytical skills",
  "technical writing",
  "data analysis",
  "presentation skills",
  "customer service",
  "active listening",
  "strategic planning",
  "self-motivation",
  "goal setting",
  "public speaking",
  "flexibility",
  "innovation",
  "prioritization",
  "mentoring",
  "delegation",
  "research skills",
  "writing skills",
  "troubleshooting",
  "coding",
  "programming",
  "data visualization",
  "quality assurance",
  "financial management",
  "sales skills",
  "marketing skills",
  "design skills",
  "software development",
  "UX/UI design",
  "database management",
  "cybersecurity",
  "IT support",
  "networking",
  "cloud computing",
  "machine learning",
  "AI development",
  "SEO optimization",
  "content creation",
  "social media management",
  "product management",
  "digital marketing",
  "brand management",
  "graphic design",
  "video editing",
  "copywriting",
  "foreign languages",
  "translation",
  "training and development",
  "business analysis",
  "process improvement",
  "lean methodologies",
  "agile methodologies",
  "Scrum",
  "DevOps",
  "financial analysis",
  "accounting",
  "human resources",
  "event planning",
  "legal research",
  "contract negotiation",
  "market research",
  "statistical analysis",
  "budgeting",
  "supply chain management",
  "logistics",
  "inventory management",
  "customer relationship management (CRM)",
  "Python",
  "JavaScript",
  "HTML",
  "CSS",
  "SQL",
  "Java",
  "C++",
  "Ruby",
  "PHP",
  "Swift",
  "Kotlin",
  "R programming",
  "Power BI",
  "Excel",
  "Tableau",
  "Photoshop",
  "Illustrator",
  "After Effects",
  "WordPress",
];
